name: Build Windows and Mac executables

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flask pygbif

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile app.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: gbif-app-windows
          path: dist/app.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flask pygbif

      - name: Build macOS executable
        run: |
          pyinstaller --onefile app.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: gbif-app-macos
          path: dist/app

